image: node:14.18.3

variables:
  ZUI_BUILD_IMAGE_TAG: 14-alpine
  LANGUAGE: "typescript"
  GIT_SUBMODULE_STRATEGY: recursive
  CUSTOM_NPM_RUN_ARGUMENTS: 'build:npi'
  RUN_TESTS: 'false'
  SKIP_FRONTEND_IMAGE_TEST: 'true'
  GITLAB_REGISTRY_AUTH_TOKEN: "//gitdp.zyfra.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}"
  ENABLE_APP_REGISTRATION: 'false'


include:
  - project: devops/gitlab-ci-templates
    ref: latest
    file: Settings/variables.yml

stages:
  - build
  - release

Build js image:
  stage: build
  allow_failure: false
  tags:
    - docker
  script:
    - sh /kaniko/kaniko-build
  image:
    name: "$KANIKO_IMAGE"
    entrypoint:
      - ''
  rules:
    - if: "$SKIP_KANIKO_BUILD =~ /^(true|yes|on|1)$/i"
      when: never
    - if: "$CI_COMMIT_BRANCH != null && $CI_PIPELINE_SOURCE == 'push' && $CI_OPEN_MERGE_REQUESTS
      != null"
      when: never
    - if: |-
        $LANGUAGE =~ /\b(typescript|javascript|node\.js)\b/i || (
          $LANGUAGE == null &&
          $CI_PROJECT_REPOSITORY_LANGUAGES =~ /^(typescript|javascript)\b/i
        )
      exists:
        - "{[Dd]ockerfile,[Dd]ockerfile\\.*,**/[Dd]ockerfile,**/[Dd]ockerfile\\.*}"


Build library:
  tags:
      - k8s
  stage: build
  # // include after k8s stable work
  # cache:
  #   paths:
  #     - node_modules
  #     - /cache/Cypress
  #     - node_modules/.cache/nx
  before_script:
    - npm config set $GITLAB_REGISTRY_AUTH_TOKEN
    - npm install

  script:
    - npm run all
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-ci/
  artifacts:
    expire_in: 1 day
    paths:
        - dist/

release_package:
  tags:
      - k8s
  stage: release
  only:
    - main
  before_script:
    - npm config set @$CI_PROJECT_ROOT_NAMESPACE:registry "$CI_SERVER_PROTOCOL://$CI_SERVER_HOST/api/v4/projects/$CI_PROJECT_ID/packages/npm/"
    - npm config set "//$CI_SERVER_HOST/api/v4/projects/$CI_PROJECT_ID/packages/npm/:_authToken" "$CI_JOB_TOKEN"
  script:
    - cd dist/libs/components
    - npm publish
    - cd ../schematics
    - npm publish
    - cd ../helpers
    - npm publish
    - cd ../translate
    - npm publish

  when: manual
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-ci/
